### ISSUE TITLE
Can't pick up shotgun after dropping it

### ISSUE THREAD

**Issue by Niconoko** [FeeeeK/LCAmmoCheck#1]
After pickup the gun and drop, can't move inventory slot or pickup something else later, aka stuck. (´・ω・｀)

**Comment by PunishedSnakePr** [comment]
Same here!

**Comment by drink1101** [comment]
same, I tried died and respawn but still stuck can only rejoin the game

**Comment by Re-VelatoR** [comment]
Also having this issue. When I don't get the frozen inventory and no interact bug, any guns I was previously holding disappear when I pick up another.

**Comment by axd1x8a** [comment]
Fixed in 1.1.1
