### ISSUE TITLE
Incompatibility with More Emotes

### ISSUE THREAD

**Issue by marco3102** [FeeeeK/LCAmmoCheck#3]
![image](https://github.com/FeeeeK/LCAmmoCheck/assets/116598674/5ef4be08-f4e1-4799-aa26-17990974fa80)

Checking ammo makes the shotgun disapear. When checking with third person the  shotgun is behind me.

Used to work a few updates ago.

**Comment by marco3102** [comment]
Very possibly mod related.
018d1700-23f4-0827-88d5-7c6cd4122730

**Comment by marco3102** [comment]
[log1.txt](https://github.com/FeeeeK/LCAmmoCheck/files/13962296/log1.txt)

**Comment by marco3102** [comment]
More_emotes by sligili
Is causing this.

**Comment by axd1x8a** [comment]
After some testing:
- More emotes are not compatible, and I will not be fixing this
- Any emotes mods that use `LethalEmotesAPI` work fine
- `TooManyEmotes` works fine

I suggest using TooManyEmotes or LethalEmotesAPI insted.
